# Generated by Django 4.0.4 on 2022-05-28 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LSED', '0002_alter_attendance_present_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='present_status',
            field=models.CharField(max_length=10),
        ),
        migrations.AlterField(
            model_name='notice',
            name='message',
            field=models.TextField(),
        ),
    ]
