# Generated by Django 4.0.4 on 2022-05-28 00:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LSED', '0003_alter_attendance_present_status_alter_notice_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentextra',
            name='photo',
            field=models.ImageField(default='photo.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
