# Generated by Django 4.0.4 on 2022-05-28 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LSED', '0004_studentextra_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherextra',
            name='photo',
            field=models.ImageField(default='photo.jpg', upload_to=''),
            preserve_default=False,
        ),
    ]
