# Generated by Django 4.0.4 on 2022-05-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LSED', '0005_teacherextra_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='studentextra',
            name='photo',
            field=models.ImageField(upload_to='profils_eleves/% Y/% m/% d/'),
        ),
        migrations.AlterField(
            model_name='teacherextra',
            name='photo',
            field=models.ImageField(upload_to='profils_profs/% Y/% m/% d/'),
        ),
    ]
