# Generated by Django 4.0.4 on 2022-05-28 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LSED', '0007_remove_studentextra_photo_remove_teacherextra_photo'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='teacherextra',
            options={'verbose_name': 'Elèves'},
        ),
    ]
