# Generated by Django 4.0.4 on 2022-05-29 11:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('LSED', '0008_alter_teacherextra_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'verbose_name': 'Présence'},
        ),
        migrations.AlterModelOptions(
            name='notice',
            options={'verbose_name': 'Notification'},
        ),
        migrations.AlterModelOptions(
            name='studentextra',
            options={'verbose_name': 'Elève'},
        ),
        migrations.AlterModelOptions(
            name='teacherextra',
            options={'verbose_name': 'Professeur'},
        ),
    ]
